### ISSUE TITLE
sklearn.exceptions.NotFittedError: The TF-IDF vectorizer is not fitted

### ISSUE THREAD

**Issue by an4078326** [LyubomirT/OrionBot#1]
**It doesn't work if you don't specify the train mod, I want it to already output the finished result and not train... how to fix it?**

![image](https://user-images.githubusercontent.com/125986222/227571147-f2beed13-2b72-46ea-b9d1-27509c755067.png)

**Comment by LyubomirT** [comment]
The issue you are seeing is that you didn't train the bot yet. Instead of generating a response like that, you can use the following code:

```python
from orionbot import Chatbot

bot = Chatbot(name="MyBot")

bot.train("Hello!", "Hey there!")
response = bot.get_response("Hello")
print(response) #Hi there!
```

NOTICE: I released a new update just now, make sure to run
```
pip install --upgrade orionbot
```

**Comment by an4078326** [comment]
The bot has already been trained on your version. I did it right, but he still doesn't see the file. And if you add `train` training by given words or from a file, it will start endlessly duplicating previously given words

**Comment by LyubomirT** [comment]
I just identified the issue and published the update, make sure to upgrade the package to latest version. Also, if you need to specify a custom file with training data, you can simply set the `data_file` parameter to your JSON file. By default, it uses the `training_data_qbot.json` file.
